#! /usr/bin/env bash

set -u
set -e
set -o pipefail


todo=${1:-}
item=${2:-}
description=${@:3}

[ ! -z "$todo" ] || exit 110
[ -f "$todo" ] || exit 110


#echo awk -v target=$item  -v description="${description}" -f todo-update.awk $todo
awk -v target=$item  -v description="${description}" -f todo-update.awk $todo > $todo.temp
mv $todo.temp $todo
