#! /usr/bin/env bash

set -u
set -e
set -o pipefail


todo=${1:-}
item=${2:-}

[ ! -z "$todo" ] || exit 110
[ -f "$todo" ] || exit 110

awk -v target=$item -f todo-rm.awk $todo > $todo.temp
mv $todo.temp $todo